####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### SCF Analysis
### 
### Work with Jack Sol and Min Bang
### Notes:
### 
### * In Week 11 there were 15 games, and the rank payments (for those in the rank condition) 
###   were between 3 cents and 17 cents.
### 
### * In Week 12 there were 14 games.  Rank payments were between 4 cents and 17 cents.  
###   In the sorting task, articipants were asked to put 5 games in each of groups A and B,
###   and 4 games in group C.
### 
### * In Week 13 there were 16 games.  Rank payments were between 3 cents and 18 cents.  
###   In the sorting task, participants were told to put at least 5 games in each group. 
### 
### * In Week 13, Participants in the sorting task saw code instead of the team names for 
###   one game (Saints @ Seahawks) when they sorted into groups.  The team names did show up 
###   for the choosing and confidence task.  Maybe we eliminate that game from the analysis.
### 
### * When you download the data, you can exclude all the data that does not have a vid number.  
###   This is the Clearvoice participant number that we use to pay participants.  If we want 
###   additional demogs, we can also request them using this number.
### 
### * I’ll need a spread sheetsheet of all vid numbers who should get paid, and what 
###   there bonuses should be.  If there are incompletes, let me those the vid numbers
###   associated with those as well. 
### 
### * Any vid number starting with a “P” is a test run by Clearvoice.  
###   These can be deleted.  Observations missing a vid number were probably generated by us.
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
library(data.table)
library(plyr)
library(reshape2)
library(ggplot2)
options(stringsAsFactors = FALSE)

# Read data
wk11  <- read.csv("http://samswift.org/data/SCF-wk11-data-2013-12-05.csv")
wk12  <- read.csv("http://samswift.org/data/SCF-wk12-data-2013-12-05.csv")
wk13  <- read.csv("http://samswift.org/data/SCF-wk13-data-2013-12-05.csv")
wk14  <- read.csv("http://samswift.org/data/SCF-wk14-data-2013-12-09.csv") 
games <- read.csv("http://samswift.org/data/SCF-games.csv")

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### Clean & Process Data
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Remove qualtrics' second header row
wk11.headers <- wk11[ 1,]
wk11         <- wk11[-1,]
wk12.headers <- wk12[ 1,]
wk12         <- wk12[-1,]
wk13.headers <- wk13[ 1,]
wk13         <- wk13[-1,]
wk14.headers <- wk14[ 1,]
wk14         <- wk14[-1,]

# match game numbers from surveys to games df
wk11.games   <- data.frame(t(wk11[2, names(wk11) %in% paste("game",1:16,sep="")]),week = 11)
wk12.games   <- data.frame(t(wk12[2, names(wk12) %in% paste("game",1:16,sep="")]),week = 12)
wk13.games   <- data.frame(t(wk13[1, names(wk13) %in% paste("game",1:16,sep="")]),week = 13)
wk14.games   <- data.frame(t(wk14[1, names(wk14) %in% paste("game",1:16,sep="")]),week = 14)

# extract game_ids from the rownames (e.g. "game15" --> 15)
wk11.games$game_id <- as.numeric(substr(row.names(wk11.games),5, nchar(row.names(wk11.games))))
wk12.games$game_id <- as.numeric(substr(row.names(wk12.games),5, nchar(row.names(wk12.games))))
wk13.games$game_id <- as.numeric(substr(row.names(wk13.games),5, nchar(row.names(wk13.games))))
wk14.games$game_id <- as.numeric(substr(row.names(wk14.games),5, nchar(row.names(wk14.games))))

names(wk11.games)[1] <- names(wk12.games)[1] <- names(wk13.games)[1] <- names(wk14.games)[1] <- "game"
s.games <- rbind(wk11.games, wk12.games)
s.games <- rbind(s.games, wk13.games)
s.games <- rbind(s.games, wk14.games)
row.names(s.games) <- NULL

s.games$away_team <- sapply(sapply(s.games$game, strsplit, split=" @ "), function(m) m[1])
s.games$home_team <- sapply(sapply(s.games$game, strsplit, split=" @ "), function(m) m[2])
s.games$game <- NULL

games <- join(games, s.games, by=c("week","away_team","home_team"))


# Define fields we actually want
id.fields       <- c("V6","V8","V9","vid","cond","text3","week")
id.names        <- c("ip_address","start_date","end_date","vid","cond","prob_phrase","week")
response.fields <- c(paste("sort",1:16,"Group",    sep="_"), 
                     paste("rank",1:16,"Rank",     sep="_"),
                     paste("Q",1:16,".1_2",        sep=""),
                     paste("Q",1:16,".2_2_1_TEXT", sep=""))
response.names  <- c(paste("sort",1:16,sep=""),
                     paste("rank",1:16,sep=""),
                     paste("pick",1:16,sep=""),
                     paste("prob",1:16,sep=""))

# Select desired variables and combine data.frames
wk11 <- wk11[names(wk11) %in% c(id.fields, response.fields)]
wk12 <- wk12[names(wk12) %in% c(id.fields, response.fields)]
wk13 <- wk13[names(wk13) %in% c(id.fields, response.fields)]
wk14 <- wk14[names(wk14) %in% c(id.fields, response.fields)]

wk11$week <- 11
wk12$week <- 12
wk13$week <- 13
wk14$week <- 14

scf <- rbind.fill(wk11, wk12)
scf <- rbind.fill(scf, wk13)
scf <- rbind.fill(scf, wk14)
scf <- scf[c(id.fields, response.fields)]
names(scf) <- c(id.names, response.names)

# Fill in prob_phrase condition for weeks 11-13 since it wasn't introduced until wk14
scf$prob_phrase[is.na(scf$prob_phrase) & scf$week %in% 11:13] <- "confidence"

# Melt data to long format
scf <- melt(scf,id.vars=id.names, varnames=response.names)
scf$variable <- as.character(scf$variable)
scf$value    <- as.numeric(scf$value)

# Remove invalid rows
scf <- scf[nchar(scf$vid) == 36 &                     # vid must be 36 characters
           !is.na(scf$value) &                        # throw out non-responses (?)
           scf$cond %in% c("control","rank","sort") & # condition must be assigned
           scf$prob_phrase %in% c("confidence", "chances"),] # condition must be assigned

# Break "variable" into response and game
scf$game_id  <- as.numeric(substr(scf$variable, 5, nchar(scf$variable)))
scf$response <- substr(scf$variable, 1, 4)
scf$variable <- NULL
xtabs(data = scf, ~ game_id + response)
xtabs(data = scf, ~ week    + response)
xtabs(data = scf, ~ game_id + week)
xtabs(data = scf, ~ response + prob_phrase + week)

# Cast back into semi-wide format (participants + week + game ~ responses) and merge game data
scf      <- dcast(scf, vid + cond + prob_phrase + week + game_id ~ response, value.var="value")
scf$pick <- factor(scf$pick,levels=1:2, labels=c("away","home")) # the home team was always displayed second
scf      <- join(scf, games[c("week","game_id","winner","avg_prob_home")], by=c("week","game_id"))

### Calculate accuracy metrics
# pick the winner, get a "hit"
scf$hit <- 0
scf$hit[scf$pick == scf$winner] <- 1

# probability assigned to the home team (100-prob if they picked the away team)
scf$prob_home <- scf$prob 
scf$prob_home[scf$pick == "away" 
              & !is.na(scf$prob_home)] <- 100 - scf$prob_home[scf$pick == "away"
                                                              & !is.na(scf$prob_home)]

# probability assigned to the winning team (100-prob if they picked the loser)
scf$prob_correct <- scf$prob_home
scf$prob_correct[scf$winner == "away"] <- 100 - scf$prob_home[scf$winner == "away"]

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### Calculate payouts
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

scf$payout <- NA
# misses always earn 0
scf$payout[scf$hit == 0] <- 0
# all hits in the control condition earn .10
scf$payout[scf$hit == 1 & scf$cond == "control"] <- .10
# hits in the sort condition are paid .5, .10, or .15
scf$payout[scf$hit == 1 & scf$cond == "sort" & scf$sort == 0] <- .15
scf$payout[scf$hit == 1 & scf$cond == "sort" & scf$sort == 1] <- .10
scf$payout[scf$hit == 1 & scf$cond == "sort" & scf$sort == 2] <- .05
# hits in the rank condition are paid based on rank
# the number of ranking options varies by week, so the payout is centered at .10
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 1]  <- .17
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 2]  <- .16
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 3]  <- .15
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 4]  <- .14
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 5]  <- .13
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 6]  <- .12
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 7]  <- .11
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 8]  <- .10
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 9]  <- .09
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 10] <- .08
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 11] <- .07
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 12] <- .06
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 13] <- .05
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 14] <- .04
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 11 & scf$rank == 15] <- .03
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 1]  <- .17
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 2]  <- .16
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 3]  <- .15
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 4]  <- .14
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 5]  <- .13
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 6]  <- .12
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 7]  <- .11
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 8]  <- .10
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 9]  <- .09
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 10] <- .08
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 11] <- .07
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 12] <- .06
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 13] <- .05
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 12 & scf$rank == 14] <- .04
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 1]  <- .18
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 2]  <- .17
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 3]  <- .16
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 4]  <- .15
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 5]  <- .14
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 6]  <- .13
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 7]  <- .12
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 8]  <- .11
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 9]  <- .10
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 10] <- .09
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 11] <- .08
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 12] <- .07
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 13] <- .06
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 14] <- .05
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 15] <- .04
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 13 & scf$rank == 16] <- .03
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 1]  <- .17
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 2]  <- .16
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 3]  <- .15
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 4]  <- .14
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 5]  <- .13
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 6]  <- .12
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 7]  <- .11
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 8]  <- .10
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 9]  <- .09
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 10] <- .08
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 11] <- .07
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 12] <- .06
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 13] <- .05
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 14] <- .04
scf$payout[scf$hit == 1 & scf$cond == "rank" & scf$week == 14 & scf$rank == 15] <- .03

write.csv(scf, "~/Desktop/scf_processed.csv", row.names=F)

# calculate total payment per participant
scf          <- data.table(scf, key="vid,cond,week")
payout.indiv <- scf[, list(cond         = cond[1],
                           n_responses  = .N,
                           n_hits       = sum(hit),
                           n_na         = sum(is.na(payout)),
                           total_payout = sum(payout, na.rm=T)), 
                    by="vid,week"]

setkeyv(payout.indiv, c("week","vid"))
write.csv(payout.indiv, "~/Desktop/scf_payout_indiv_wk11-14.csv", row.names = F)

####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### Hypothesis Tests
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# did hit rate vary by condition?
hit.cond <- scf[, list(hit_rate = mean(hit)), by=cond]
chisq.test(x=scf$cond, y=scf$hit)
summary(glm(hit ~ prob + cond, data=scf, family="binomial"))

# did payout vary by condition?
pay.cond <- scf[, list(mean_pay = mean(payout, na.rm=T),
                       sd_pay   = sd(payout, na.rm=T),
                       n        = .N)
                , by=cond]
summary(aov(payout ~ cond, data=scf))

# did calibration vary by condition?
scf$bin      <- round(scf$prob / 5) * 5
hit.cond.bin <- scf[, list(hit_rate = mean(hit), n = .N), by="cond,bin"]
hit.cond.bin <- hit.cond.bin[bin >= 50,]

ggplot(hit.cond.bin, aes(bin, hit_rate*100, color=cond)) + 
  geom_abline(intercept=.50, slope=1) +
  scale_x_continuous(limit=c(45,100), breaks=seq(45,100,5)) +
  scale_y_continuous(limit=c(45,100), breaks=seq(45,100,5)) +
  geom_point(aes(size = n), shape=19) + 
  geom_smooth(se=F, size=1.25) +
  labs(x="Confidence", y="Hit Rate", size="N Obs", color="Condition", title="Calibration by Condition\nSCF, weeks 11-14") +
  theme_bw(base_size=16)

# does correlation to betting lines vary by condition?
ggplot(scf, aes(prob_home, avg_prob_home, color=cond)) +
  geom_point(position="jitter", alpha=.5) +
  geom_smooth(method="lm", se=F) +
  theme_bw()

cor(scf$prob_home, scf$avg_prob_home,use="complete.obs")

# does the question framing (started in week 14) change the dist of forecasts
ggplot(scf[week == 14,], aes(prob, fill = prob_phrase)) + 
  geom_histogram(position="dodge", breaks=seq(50,100, 1)) +
  labs(x="Expressed Probability", y="Count", fill="Response Phrase", title="Week 14 response frequencies by response phrase") +
  theme_bw(base_size=18)

