####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
### SCF Analysis
###
### Work with Jack Sol and Min Bang
### Notes:
### The number of games changed each week.
# 
# In Week 11 there were 15 games, and the rank payments (for those in the rank condition) 
# were between 3 cents and 17 cents.
# 
# In Week 12 there were 14 games.  Rank payments were between 4 cents and 17 cents.  
# In the sorting task, articipants were asked to put 5 games in each of groups A and B,
# and 4 games in group C.
# 
# In Week 13 there were 16 games.  Rank payments were between 3 cents and 18 cents.  
# In the sorting task, participants were told to put at least 5 games in each group. 
# 
# In Week 13, Participants in the sorting task saw code instead of the team names for 
# one game (Saints @ Seahawks) when they sorted into groups.  The team names did show up 
# for the choosing and confidence task.  Maybe we eliminate that game from the analysis.
# 
# When you download the data, you can exclude all the data that does not have a vid number.  
# This is the Clearvoice participant number that we use to pay participants.  If we want 
# additional demogs, we can also request them using this number.
# 
# I’ll need a spread sheetsheet of all vid numbers who should get paid, and what 
# there bonuses should be.  If there are incompletes, let me those the vid numbers
# associated with those as well. 
# 
# Any vid number starting with a “P” is a test run by Clearvoice.  
# These can be deleted.  Observations missing a vid number were probably generated by us.
####~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
library(data.table)
library(plyr)
library(reshape2)
options(stringsAsFactors = FALSE)

# Read data
wk11  <- read.csv("http://samswift.org/data/SCF-wk11-data-2013-12-05.csv")
wk12  <- read.csv("http://samswift.org/data/SCF-wk12-data-2013-12-05.csv")
wk13  <- read.csv("http://samswift.org/data/SCF-wk13-data-2013-12-05.csv")
games <- read.csv("http://samswift.org/data/SCF-games-2013-12-05.csv")

# Remove qualtrics' second header row
wk11.headers <- wk11[ 1,]
wk11         <- wk11[-1,]
wk12.headers <- wk12[ 1,]
wk12         <- wk12[-1,]
wk13.headers <- wk13[ 1,]
wk13         <- wk13[-1,]

# Define fields we actually want
id.fields       <- c("V6","V8","V9","V10","vid","cond","week")
id.names        <- c("ip_address","start_date","end_date","finished","vid","cond","week")
response.fields <- c(paste("sort",1:16,"Group",    sep="_"), 
                     paste("sort",1:16,"Rank",     sep="_"),
                     paste("Q",1:16,".1_2",        sep=""),
                     paste("Q",1:16,".2_2_1_TEXT", sep=""))
response.names  <- c(paste("sort",1:16,sep=""),
                     paste("rank",1:16,sep=""),
                     paste("pick",1:16,sep=""),
                     paste("prob",1:16,sep=""))

# Select desired variables and combine data.frames
wk11 <- wk11[names(wk11) %in% c(id.fields, response.fields)]
wk12 <- wk12[names(wk12) %in% c(id.fields, response.fields)]
wk13 <- wk13[names(wk13) %in% c(id.fields, response.fields)]

wk11$week <- 11
wk12$week <- 12
wk13$week <- 13

scf <- rbind.fill(wk11, wk12)
scf <- rbind.fill(scf, wk13)
scf <- scf[c(id.fields, response.fields)]
names(scf) <- c(id.names, response.names)

# Melt data to long format
scf <- melt(scf,id.vars=id.names, varnames=response.names)
scf$variable <- as.character(scf$variable)
scf$value    <- as.numeric(scf$value)

# Remove invalid rows
scf <- scf[nchar(scf$vid) == 36 &                     # vid must be 36 characters
           !is.na(scf$value) &                        # throw out non-responses (?)
           scf$cond %in% c("control","rank","sort"),] # condition must be assigned

# Identify game value from variable names
scf$game <- as.numeric(substr(scf$variable, 5, nchar(scf$variable)))
xtabs(data = scf, ~ game + week)



