SQEF (Status Quo Endorsement, Football) Results
========================================================

### Abstract
Participants forecast the probability that last year's NFL division champions would repeat as champions this year.  Participants asked about the probability of the status quo persisting reported higher probabilities of the status quo compared to those who were asked about the probability of change.  There was no significant differnce in forecasts as a result of the specific items being described as selected by an NFL expert or randomly by an expert.

### Intro

SQEF tests two hypotheses concerning participants' forecasts of questions in which the outcomes correspond to either Status Quo or change.  Earlier observations suggest that participants under-forecat status quo options.  This study tests two explanations for that tendency:

1. Question framing leads responses.  We hypothesize that partcipants are more likely to forecast the status quo if the forecast asks about the status quo (e.g. "What is the probability that X will remain in power") than if it asks about the probability of a changed state (e.g. "What is the probability that X will fall out of power").

2. Question selection implies change.  We hypothesize that a non-random selection of forecast problems conveys information about the liklihood of change in those situations.  It seems reasonable to infer that if an expert selected a specific item for forecasting, it may not be representative of the baserate distribution of change from the status quo across all such cases.

We used the context of the NFL football season to test these two explanations of status quo forecasting behavior.

### Sample
``` {r message=FALSE, results='hide', warning=FALSE, fig.keep='none'}
source("SQEF Analysis.R")
```

`r total.n` participants responded to soliciations posted on Amazon's mturk (n= `r total.n.src["mturk"]` ) and reddit.com's NFL fan community(n= `r total.n.src["reddit"]`).  Participants were recruited from both sites to ensure that we sampled sufficiently across the range of NFL fandom to enable expertise-related analyses.  All participants completed the study on September 5th, 2012, the day of the first NFL game of the 2012 season.

Participants were excluded from the analysis if they exited the study before making forecasts (n= `r excl.incomplete`), completed the entire study in fewer than 30 seconds (n= `r excl.time`), or may have been participating more than once as determined by duplicate IP addresses (n= `r excl.dup`).  Because these exclusion criteria were largely redundant, the final sample numbered `r post.excl.n`. 

The final sample of `r post.excl.n` was `r round(prop.table(table(sqef$gender))["Male"],2)*100`% male.  Participants' mean age was `r round(describe(sqef$age)["mean"],2)` (SD= `r round(describe(sqef$age)["sd"],2)`), `r round(sum(prop.table(table(sqef$edu))[c("Bachelors","Masters","PhD","JD/MD")]),2)*100`% had at least a Bachelors degree, and participants currently lived in `r length(unique(sqef$geo))` US states.

#### Fanhood
Fanhood was measured in three ways

* Social comparison: Would you consider yourself more or less of a fan of the NFL than the average American? (7pt scale, from Much Less to Much More)
* Behavioral self report: Please estimate how many NFL games you watch in an average week during the regular season.
* Recruitment source: Participants recuited from the online NFL discussion community were considered NFL fans.

The three measures were highly related (standardized alpha = `r round(alpha(fan.measures)$total["std.alpha"],2)`).


### Methods








